
apiVersion: batch/v1
kind: Job
metadata:
  namespace: graphcore
  generateName: __TEMPLATE_USER__-__TEMPLATE_PROJECT__-
  labels:
    kueue.x-k8s.io/queue-name: unified
    user: __TEMPLATE_USER__
    email: __TEMPLATE_USER___at_graphcore.ai
    project: __TEMPLATE_PROJECT__
    organization: graphcore
spec:
  parallelism: 1
  completions: 1
  completionMode: Indexed
  backoffLimitPerIndex: 0  # maximal number of failures per index
  ttlSecondsAfterFinished: 7200
  template:
    metadata:
      labels:
        user: __TEMPLATE_USER__
        email: __TEMPLATE_USER___at_graphcore.ai
        project: __TEMPLATE_PROJECT__
        organization: graphcore
    spec:
      # Pass dictionary, e.g. {nvidia.com/gpu.clique: clique-id}
      nodeSelector: __TEMPLATE_NODE_SELECTOR__
      runtimeClassName: nvidia
      tolerations:
      - key: "kueue.x-k8s.io/dedicated"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      containers:
      - name: worker
        image: nvidia/cuda:12.9.1-cudnn-devel-ubuntu22.04
        env: __TEMPLATE_ENV__
        command:
          - bash
          - -c
          - |
            # Write code to job.pkl
            base64 -d > ~/job.pkl <<'__B64__'
            __TEMPLATE_JOB__
            __B64__
            
            # Install system dependencies
            apt-get update
            apt-get install -y build-essential git curl unzip python3-dev python3.10-venv
            curl https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip -o awscliv2.zip
            unzip -q awscliv2.zip
            ./aws/install
            rm -rf ./aws awscliv2.zip
            
            # Settings to speed up fetching from s3
            aws configure set default.s3.multipart_chunksize 16MB
            aws configure set default.s3.preferred_transfer_client crt
            aws configure set default.s3.target_bandwidth 50GB/s
            
            # Initialise repository and install Python dependencies
            cd ~
            git -c url."https://${GITHUB_TOKEN}@github.com/".insteadOf=git@github.com: clone --recursive https://${GITHUB_TOKEN}@github.com/graphcore-research/squashed-llama.git
            cd squashed-llama/training
            git checkout --recurse-submodules ${GIT_COMMIT}
            python3 -m venv .venv
            echo "export PYTHONPATH=\${PYTHONPATH}:\$(dirname \${VIRTUAL_ENV})/optimal_weight_formats" >> .venv/bin/activate
            source .venv/bin/activate
            pip install --upgrade pip wheel
            pip install -r requirements.txt
            
            # Run the job
            python cluster/_run_job.py
        resources:
          requests:
            nvidia.com/gpu: __TEMPLATE_GPUS__
            memory: __TEMPLATE_MEMORY__
            cpu: __TEMPLATE_CPUS__
          limits:
            nvidia.com/gpu: __TEMPLATE_GPUS__
            memory: __TEMPLATE_MEMORY__
            cpu: __TEMPLATE_CPUS__
      restartPolicy: Never
