#!/usr/bin/env python3

import argparse
import platform
import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any, Callable, Iterable, List, TypeVar


###############################################################################
# Common

T = TypeVar("T")


def _run(
    command: Iterable[Any], env: dict[str, str] = {}, stdout_to_stderr: bool = False
) -> None:
    """Run a command, terminating on failure."""
    cmd = [str(arg) for arg in command if arg is not None]
    print("$ " + " ".join(cmd), file=sys.stderr)
    environ = os.environ.copy()
    environ["PYTHONPATH"] = f"{os.getcwd()}:{environ.get('PYTHONPATH', '')}"
    environ.update(env)
    exit_code = subprocess.call(
        cmd,
        env=environ,
        stdout=(sys.stderr if stdout_to_stderr else None),
    )
    if exit_code:
        sys.exit(exit_code)


def _push_to_device(src: Path) -> Path:
    """Push a file to an attached Android device"""
    dest = Path(f"/data/local/tmp/{src.name}")
    _run(["adb", "push", str(src), str(dest)])
    return dest


def _run_on_device(command: Iterable[Any], env: dict[str, str]) -> None:
    """Run on an attached Android device"""
    program, *args = command
    program = _push_to_device(Path(program))
    args_str = " ".join(str(arg) for arg in args if arg is not None)
    _run(
        [
            "adb",
            "shell",
            f"cd {program.parent} && env LD_LIBRARY_PATH={program.parent}"
            f" ./{program.name} {args_str}",
        ],
        env=env,
    )


def _run_under_gdb(command: Iterable[Any], env: dict[str, str]) -> None:
    """Run under GDB (on host)"""
    _run(["gdb", "-ex", "run", "--args", *command], env=env)


def _run_target(
    command: Iterable[Any], env: dict[str, str], platform: str, gdb: bool
) -> None:
    """Run the command on the given platform, optionally under gdb"""
    if platform == "android":
        assert not gdb, "gdb not supported on android"
        _run_on_device(command, env)
    elif gdb:
        _run_under_gdb(command, env)
    else:
        _run(command, env)


def cli(*args: Any, **kwargs: Any) -> Callable[[T], T]:
    """Declare a CLI command / arguments for that command."""

    def wrap(func: T) -> T:
        if not hasattr(func, "cli_args"):
            setattr(func, "cli_args", [])
        if args or kwargs:
            getattr(func, "cli_args").insert(0, (args, kwargs))
        return func

    return wrap


BUILD = Path("build")
SRC = Path("src")
ANDROID_NDK = Path("/opt/android-sdk/ndk/latest")
PLATFORMS = ["release", "debug"] + (["android"] if ANDROID_NDK.exists() else [])
THIRD_PARTY_SOURCES = (
    "https://raw.githubusercontent.com/nlohmann/json/refs/tags/v3.11.3/single_include/nlohmann/json.hpp",
    "https://raw.githubusercontent.com/ninja-build/ninja/refs/tags/v1.12.1/misc/ninja_syntax.py",
    "https://raw.githubusercontent.com/catchorg/Catch2/refs/tags/v3.7.1/extras/catch_amalgamated.hpp",
    "https://raw.githubusercontent.com/catchorg/Catch2/refs/tags/v3.7.1/extras/catch_amalgamated.cpp",
    "https://github.com/jarro2783/cxxopts/raw/refs/tags/v3.2.1/include/cxxopts.hpp",
    "https://raw.githubusercontent.com/nothings/stb/013ac3beddff3dbffafd5177e7972067cd2b5083/stb_image.h",
    "https://raw.githubusercontent.com/nothings/stb/2e2bef463a5b53ddf8bb788e25da6b8506314c08/stb_image_resize2.h",
)

###############################################################################
# Commands


@cli()
def setup(platforms: List[str]) -> None:
    """download third-party libraries"""
    third_party = Path("third-party")
    third_party.mkdir(exist_ok=True)
    for path in THIRD_PARTY_SOURCES:
        _run(["wget", "-nv", "-O", third_party / Path(path).name, path])


@cli()
def clean(platforms: List[str]) -> None:
    """clean up generated files"""
    for platform in platforms:
        build = BUILD / platform
        if build.exists():
            shutil.rmtree(build)
    if not list(BUILD.iterdir()):
        BUILD.rmdir()


def _generate_build_ninja(w: Any, platform: str) -> None:
    cxx = (
        ANDROID_NDK / "toolchains/llvm/prebuilt/linux-x86_64/bin/clang++"
        if platform == "android"
        else os.getenv("CXX", "clang++")
    )
    flags, cxxflags, linkflags, libs = [], [], [], []
    cxxflags += ["$flags", "-fcolor-diagnostics", "-fdiagnostics-absolute-paths"]
    cxxflags += ["-Wall", "-Wextra", "-Wconversion", "-Wdouble-promotion", "-Werror"]
    cxxflags += [f"-I$src", f"-isystem $third-party"]
    cxxflags += ["-g", "-fPIC", "-std=c++20"]
    cxxflags += ["-O0"] if "debug" in platform else ["-O3", "-DNDEBUG"]
    cxxflags += ["-fdata-sections", "-ffunction-sections"]
    linkflags += ["$flags"]
    linkflags += ["-Wl,--gc-sections", "-Wl,--fatal-warnings", "-Wl,--no-undefined"]
    if platform != "android":
        cxxflags += [f"-mcpu=native"]
    if platform == "android":
        flags += ["--target=aarch64-linux-android35"]
        cxxflags += ["-DANDROID"]
        linkflags += ["-static-libstdc++"]
        libs += ["-llog", "-static-openmp"]
    if "clang++" in cxx:
        flags += ["-stdlib=libc++"]
    flags += ["-fopenmp"]

    root_to_files = {}  # [root] -> (src, obj, {variable: value})
    for root in ["benchmark", "core", "lib", "programs", "tests"]:
        root_to_files[root] = []
        for cpp in (s.relative_to(SRC) for s in (SRC / root).glob("**/*.cpp")):
            root_to_files[root] += [
                (f"$src/{cpp}", f"$obj/{cpp.with_suffix('.o')}", {})
            ]
    catch_cxxflags = [
        f for f in cxxflags if f not in ["-Wconversion", "-Wdouble-promotion"]
    ]
    root_to_files["catch"] = [
        (
            "$third-party/catch_amalgamated.cpp",
            "$obj/catch/catch_amalgamated.o",
            dict(cxxflags=catch_cxxflags),
        )
    ]

    # Variables
    w.variable("src", f"../../{SRC}")
    w.variable("third-party", "../../third-party")
    w.variable("obj", "obj")
    w.variable("cxx", cxx)
    w.variable("libs", libs)
    w.variable("flags", flags)
    w.variable("cxxflags", cxxflags)
    w.variable("linkflags", linkflags)
    w.newline()

    # Rules
    w.rule(
        "compile",
        command="$cxx -MMD -MT $out -MF $out.d $cxxflags -c $in -o $out",
        description="CXX $out",
        depfile="$out.d",
        deps="gcc",
    )
    w.rule(
        "compile_asm",
        command="$cxx -MMD -MT $out -MF $out.d $cxxflags -S $in -o $out",
        description="ASM $out",
        depfile="$out.d",
        deps="gcc",
    )
    w.rule(
        "linkexe",
        command="$cxx $in $linkflags -o $out $libs",
        description="LINKEXE $out",
    )
    w.rule(
        "linkso",
        command="$cxx $in $linkflags -shared -o $out $libs",
        description="LINKSO $out",
    )
    w.rule(
        "runpy",
        command="python3 $in $out",
        description="PYTHON $in",
    )
    w.newline()

    # Objects
    for cpp, obj, vars in (v for vs in root_to_files.values() for v in vs):
        w.build(obj, "compile", cpp, variables=vars)
        w.build(
            f"{obj}.s",
            "compile_asm",
            cpp,
            variables={
                **vars,
                "cxxflags": [
                    f for f in vars.get("cxxflags", cxxflags) if f not in ["-g"]
                ],
            },
        )
    w.newline()

    # Programs & shared libraries
    binaries = [
        ("cli", "linkexe", ["core", "lib"]),
        ("benchmark", "linkexe", ["core", "lib", "benchmark"]),
        ("tests", "linkexe", ["core", "lib", "benchmark", "tests", "catch"]),
        ("libsquashed-llama.so", "linkso", ["core", "lib"]),
    ]
    for name, rule, roots in binaries:
        objs = [obj for root in roots for _, obj, _ in root_to_files[root]]
        objs += [
            obj
            for src, obj, _ in root_to_files["programs"]
            if src.endswith(f"{name}.cpp")
        ]
        w.build(name, rule, objs)

    # Test data
    w.build("testdata.bin", "runpy", "$src/tests/core/gentest_tensor_data.py")


@cli("targets", nargs="*", help="build targets")
@cli("-v", "--verbose", action="store_true", help="enable verbose output")
def build(platforms: List[str], targets: List[str], verbose: bool) -> None:
    """build C++ code"""
    third_party = str(Path(__file__).parent / "third-party")
    if third_party not in sys.path:
        sys.path.append(third_party)
    import ninja_syntax

    for platform in platforms:
        root = BUILD / platform
        root.mkdir(parents=True, exist_ok=True)
        with (root / "build.ninja").open("w") as file:
            _generate_build_ninja(ninja_syntax.Writer(file), platform)
        _run(
            ["ninja", "-C", root, *targets, "--verbose" if verbose else None],
            stdout_to_stderr=True,
        )


@cli(
    "args",
    nargs="*",
    help="arguments for Catch2"
    "(https://github.com/catchorg/Catch2/blob/devel/docs/command-line.md)",
)
@cli("--gdb", action="store_true", help="run under gdb")
def tests(platforms: List[str], gdb: bool, args: List[str]) -> None:
    """run unit tests"""
    build(platforms=platforms, targets=["tests", "testdata.bin"], verbose=False)
    for platform in platforms:
        testdata = BUILD / platform / "testdata.bin"
        if platform == "android":
            testdata = _push_to_device(testdata)
        _run_target(
            [BUILD / platform / "tests", *args],
            env=dict(TESTDATA=str(testdata)),
            platform=platform,
            gdb=gdb,
        )


@cli("program", help="program to run (see src/programs)")
@cli("args", nargs="*", help="arguments")
@cli("--gdb", action="store_true", help="run under gdb")
def run(platforms: List[str], program: str, gdb: bool, args: List[str]) -> None:
    """build and run the given program"""
    build(platforms=platforms, targets=[program], verbose=False)
    for platform in platforms:
        _run_target(
            [BUILD / platform / program, *args], env={}, platform=platform, gdb=gdb
        )


@cli("-i", "--incremental", action="store_true", help="disable 'clean' before build")
def ci(platforms: List[str], incremental: bool) -> None:
    """run all CI checks"""
    if not incremental:
        clean(platforms=platforms)
    tests(platforms=platforms, gdb=False, args=[])
    run(platforms=platforms, program="benchmark", gdb=False, args=[])


################################################################################
# Driver


def _main() -> None:
    # Build an argparse command line by finding globals in the current module
    # that are marked via the @cli() decorator. Each one becomes a subcommand
    # running that function, usage "$ ./dev fn_name ...args".
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "-p",
        "--platform",
        choices=PLATFORMS + ["all"],
        action="append",
        dest="platforms",
        help=f"platforms to build (default: [{PLATFORMS[0]}])",
    )
    parser.set_defaults(
        _action=lambda platforms: ci(platforms=platforms, incremental=True)
    )

    subs = parser.add_subparsers()
    for key, value in globals().items():
        if hasattr(value, "cli_args"):
            sub = subs.add_parser(key.replace("_", "-"), help=value.__doc__)
            for args, kwargs in value.cli_args:
                sub.add_argument(*args, **kwargs)
            sub.set_defaults(_action=value)

    cli_args = vars(parser.parse_args())
    if not cli_args["platforms"]:
        cli_args["platforms"] = [PLATFORMS[0]]
    elif "all" in cli_args["platforms"]:
        cli_args["platforms"] = PLATFORMS
    _action = cli_args.pop("_action")
    _action(**cli_args)


if __name__ == "__main__":
    _main()
